# Generated by Django 4.2.16 on 2026-02-20 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("OPENING", "Opening Balance"),
                            ("PURCHASE", "Purchase"),
                            ("PRODUCTION", "Production"),
                            ("ADJUSTMENT_ADD", "Manual Add"),
                            ("ADJUSTMENT_SUB", "Manual Subtract"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                ("balance_qty", models.DecimalField(decimal_places=4, max_digits=15)),
                ("balance_value", models.DecimalField(decimal_places=4, max_digits=20)),
                ("reference_no", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "raw_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="master.rawmaterial",
                    ),
                ),
            ],
            options={
                "db_table": "stock_ledger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=15)),
                ("batch_no", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scrap_entries",
                        to="master.productmodel",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scrap_entries",
                        to="production.productionorder",
                    ),
                ),
            ],
            options={
                "db_table": "scrap_stock",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateField()),
                ("supplier_name", models.CharField(max_length=200)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=15)),
                ("purchase_rate", models.DecimalField(decimal_places=4, max_digits=15)),
                ("total_amount", models.DecimalField(decimal_places=4, max_digits=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "raw_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="master.rawmaterial",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_entries",
                "ordering": ["-purchase_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[("ADD", "Add Stock"), ("SUBTRACT", "Subtract Stock")],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=15)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "raw_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="master.rawmaterial",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_adjustments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinishedGoodsStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=15)),
                ("batch_no", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fg_stock",
                        to="master.productmodel",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fg_entries",
                        to="production.productionorder",
                    ),
                ),
            ],
            options={
                "db_table": "finished_goods_stock",
                "ordering": ["-created_at"],
            },
        ),
    ]
