# Generated by Django 4.2.16 on 2026-03-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseentry",
            name="gst_percent",
            field=models.IntegerField(
                choices=[(0, "0%"), (5, "5%"), (18, "18%")], default=18
            ),
        ),
    ]
