# Generated by Django 4.2.16 on 2026-02-20 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_no", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField()),
                ("qty_planned", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "qty_produced",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "qty_rejected",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                ("batch_no", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                (
                    "batch_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_orders",
                        to="master.productmodel",
                    ),
                ),
            ],
            options={
                "db_table": "production_orders",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionMaterialUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty_used", models.DecimalField(decimal_places=4, max_digits=15)),
                ("rate", models.DecimalField(decimal_places=4, max_digits=15)),
                ("cost", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_usage",
                        to="production.productionorder",
                    ),
                ),
                (
                    "raw_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_usage",
                        to="master.rawmaterial",
                    ),
                ),
            ],
            options={
                "db_table": "production_material_usage",
            },
        ),
    ]
