# Generated by Django 4.2.16 on 2026-02-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_id", models.CharField(max_length=50, unique=True)),
                ("model_name", models.CharField(max_length=200)),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "product_models",
                "ordering": ["model_name"],
            },
        ),
        migrations.CreateModel(
            name="RawMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.CharField(max_length=50, unique=True)),
                ("item_name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ELECTRICAL", "Electrical"),
                            ("MECHANICAL", "Mechanical"),
                            ("HARDWARE", "Hardware"),
                            ("PACKAGING", "Packaging"),
                            ("CONSUMABLE", "Consumable"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("PCS", "Pieces"),
                            ("KG", "Kilograms"),
                            ("MTR", "Meters"),
                            ("LTR", "Litres"),
                            ("SET", "Set"),
                            ("ROLL", "Roll"),
                            ("BOX", "Box"),
                            ("GM", "Grams"),
                            ("MM", "Millimeters"),
                        ],
                        default="PCS",
                        max_length=20,
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "default_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "lead_time",
                    models.IntegerField(default=0, help_text="Lead time in days"),
                ),
                ("status", models.BooleanField(default=True)),
                (
                    "current_stock",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "moving_avg_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "raw_materials",
                "ordering": ["item_name"],
            },
        ),
    ]
