# Generated by Django 4.2.16 on 2026-03-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawmaterial",
            name="category",
            field=models.CharField(
                choices=[
                    ("ELECTRICAL", "Electrical"),
                    ("MECHANICAL", "Mechanical"),
                    ("HARDWARE", "Hardware"),
                    ("PACKAGING", "Packaging"),
                    ("CONSUMABLE", "Consumable"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="rawmaterial",
            name="item_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="rawmaterial",
            name="item_name",
            field=models.CharField(max_length=300),
        ),
    ]
