# Generated by Django 4.2.16 on 2026-03-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "master",
            "0002_alter_rawmaterial_category_alter_rawmaterial_item_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawmaterial",
            name="category",
            field=models.CharField(
                choices=[
                    ("ELECTRICAL", "Electrical"),
                    ("MECHANICAL", "Mechanical"),
                    ("HARDWARE", "Hardware"),
                    ("PACKAGING", "Packaging"),
                    ("CONSUMABLE", "Consumable"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="rawmaterial",
            name="current_stock",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name="rawmaterial",
            name="default_cost",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name="rawmaterial",
            name="item_id",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="rawmaterial",
            name="item_name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="rawmaterial",
            name="moving_avg_cost",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name="rawmaterial",
            name="reorder_level",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name="rawmaterial",
            name="unit",
            field=models.CharField(
                choices=[
                    ("PCS", "Pieces"),
                    ("KG", "Kilograms"),
                    ("MTR", "Meters"),
                    ("LTR", "Litres"),
                    ("SET", "Set"),
                    ("ROLL", "Roll"),
                    ("BOX", "Box"),
                    ("GM", "Grams"),
                    ("MM", "Millimeters"),
                ],
                default="PCS",
                max_length=50,
            ),
        ),
    ]
